### ISSUE TITLE
does it work?

### ISSUE THREAD

**Issue by OuyangJunyuan** [ckflight/NRF24_Transceiver_Hardware#1]
I need pa for my nrf,but i don't know how to designt it . if it work , i would like to change it with my code, i think my code is good

**Comment by ckflight** [comment]
It is working no problem. You can use the amplifier design on the schematic. I did not make a range test though.

**Comment by OuyangJunyuan** [comment]
Thanks.
it was needed impedance matching from PA to ANT?
pardon my&nbsp;pool&nbsp;english



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cenk Keskin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 晚上8:39
收件人:&nbsp;"ckflight/NRF24_TRANSCEIVER_HARDWARE"<NRF24_TRANSCEIVER_HARDWARE@noreply.github.com&gt;;
抄送:&nbsp;"706545330"<706545330@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ckflight/NRF24_TRANSCEIVER_HARDWARE] does it work? (#1)




Closed #1.

**Comment by ckflight** [comment]
It has microstrip line impedance matching is needed for each RF trace for 50 ohm transmission line. I ordered my pcb from oshpark back then. With their 4 layer stack up 50 ohm microstrip line impedance is 0.34mm.
There is also a cutout at the sma connector because pad is wide and it reflects the power back. Therefour sma pad is coupled to layer 3. It's rf design is fine as well.

**Comment by OuyangJunyuan** [comment]
emmm....i am amateur.&nbsp;
I don't know how to design a 50-ohm impedance in 2 layers PCB.
I just want to make a remote control for my little remote control car.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cenk Keskin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 晚上8:49
收件人:&nbsp;"ckflight/NRF24_TRANSCEIVER_HARDWARE"<NRF24_TRANSCEIVER_HARDWARE@noreply.github.com&gt;;
抄送:&nbsp;"706545330"<706545330@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ckflight/NRF24_TRANSCEIVER_HARDWARE] does it work? (#1)




It has microstrip line impedance matching for 50 ohm transmission line. I ordered my pcb from oshpark back then. With their 4 layer stack up 50 ohm microstrip line impedance is 0.34mm.
 There is also a cutout at the sma connector because pad is wide and it reflects the power back. Therefour sma pad is coupled to layer 3. It's rf design is fine as well.

**Comment by ckflight** [comment]
Use this link to calculate trace with for 50 ohm impedance : https://www.eeweb.com/tools/microstrip-impedance
Then add continuous ground layer under rf trace. Do not draw any other trace under rf traces that is mostly it.
Thats all i can help for you. Please search for other things in electronicstackexchange type of forums.
